-- Table: neogeo.rerousecon_l

-- DROP TABLE neogeo.rerousecon_l;

CREATE TABLE neogeo.rerousecon_l
(
  accessibilite_lineaire character varying(255),
  adresse character varying(255),
  affichage_nom character varying(255),
  affichage_sens character varying(255),
  alias_d character varying(255),
  alias_g character varying(255),
  angle double precision,
  bordure_iti character varying(255),
  bornedeb_d character varying(255),
  bornedeb_g character varying(255),
  bornefin_d character varying(255),
  bornefin_g character varying(255),
  bretelle boolean,
  cartogip_id character varying(255),
  classification character varying(255),
  cle_voie_cartogip_id character varying(255),
  cleext_voie character varying(255),
  cleext_voie_nom character varying(255),
  code_groupement character varying(255),
  code_systeme1 character varying(255),
  code_systeme2 character varying(255),
  code_systeme3 character varying(255),
  code_systeme4 character varying(255),
  code_systeme5 character varying(255),
  code_systeme6 character varying(255),
  code_systeme7 character varying(255),
  code_systeme8 character varying(255),
  code_zone_geo character varying(255),
  codepost_d character varying(255),
  codepost_g character varying(255),
  codevoie_d character varying(255),
  codevoie_g character varying(255),
  commune character varying(255),
  commune_insee character varying(255),
  coordonnees_400_x character varying(255),
  coordonnees_400_y character varying(255),
  coordonnees_utm character varying(255),
  createur character varying(255),
  creation_date date,
  creation_heure time without time zone,
  date_modif_sdis33 date,
  decalage_nom character varying(255),
  decalage_sens character varying(255),
  decalage_sens_pt character varying(255),
  decalage_x_nvh character varying(255),
  decalage_y_nvh character varying(255),
  dep24_buffer_ext boolean,
  dep33_buffer_ext boolean,
  dep40_buffer_ext boolean,
  dep47_buffer_ext boolean,
  departement character varying(255),
  derniere_action_objet character varying(255),
  derniere_modif_date date,
  derniere_modif_heure time without time zone,
  disponibilite boolean,
  document character varying(255),
  etat character varying(255),
  fictif character varying(255),
  filtre_50 character varying(255),
  fk_gip integer,
  fk_sdis33_cta integer,
  fk_sdis33_ext04 integer,
  fk_sdis33_prevision integer NOT NULL,
  fk_sdis33_ressource_en_eau integer,
  fosse character varying(255),
  fournisseur_donnee_fk character varying(255),
  fournisseur_donnee_nom character varying(255),
  franchisst character varying(255),
  identifiant_ign character varying(255),
  importance_ign character varying(255),
  inseecom_d character varying(255),
  inseecom_g character varying(255),
  integrateur character varying(255),
  inter_lettres character varying(255),
  inter_mots character varying(255),
  interet_25000 character varying(255),
  interet_50000 character varying(255),
  iti_europ character varying(255),
  justification_nom double precision,
  justification_sens double precision,
  justification_sens_pt double precision,
  largeur_emprise double precision,
  largeur_roulement double precision,
  largeur_voie double precision,
  lieu_dit_surfacique character varying(255),
  longueur_metre integer,
  nature_ign character varying(255),
  nature_physique character varying(255),
  nom character varying(255),
  nom_2 character varying(255),
  nom_3 character varying(255),
  nom_4 character varying(255),
  nom_iti character varying(255),
  nom_origine character varying(255),
  nom_rtes_principales_25_decalage_x_fleche character varying(255),
  nom_rtes_principales_25_decalage_y_fleche character varying(255),
  nom_rtes_principales_25_delta_x character varying(255),
  nom_rtes_principales_25_delta_y character varying(255),
  nom_rtes_principales_25_fleche character varying(255),
  nom_rtes_principales_25_visibilite boolean,
  nom_voie_d character varying(255),
  nom_voie_g character varying(255),
  nom_zone_geo character varying(255),
  nomroutedept_50_decalage_x_fleche character varying(255),
  nomroutedept_50_decalage_y_fleche character varying(255),
  nomroutedept_50_delta_x character varying(255),
  nomroutedept_50_delta_y character varying(255),
  nomroutedept_50_fleche character varying(255),
  nomroutedept_50_visibilite boolean,
  nomvoies_25_decalage_x_fleche character varying(255),
  nomvoies_25_decalage_y_fleche character varying(255),
  nomvoies_25_delta_x character varying(255),
  nomvoies_25_delta_y character varying(255),
  nomvoies_25_fleche character varying(255),
  nomvoies_25_visibilite boolean,
  numero_rr character varying(255),
  numero_zoom character varying(255),
  observation text,
  origine_donnee character varying(255),
  origine_maj_donnees character varying(255),
  page_atlas character varying(255),
  peage_sens character varying(255),
  peage_sens_iti character varying(255),
  pos_sol integer,
  position_nvh character varying(255),
  prec_alti double precision,
  prec_plani double precision,
  restr_hauteur double precision,
  restr_largeur double precision,
  restr_longueur double precision,
  restriction_acces_poids double precision,
  rond_point boolean,
  rotation_nvh double precision,
  routeprincipale_25_nom_sup650m_decalage_x_fleche character varying(255),
  routeprincipale_25_nom_sup650m_decalage_y_fleche character varying(255),
  routeprincipale_25_nom_sup650m_delta_x character varying(255),
  routeprincipale_25_nom_sup650m_delta_y character varying(255),
  routeprincipale_25_nom_sup650m_fleche character varying(255),
  routeprincipale_25_nom_sup650m_visibilite boolean,
  sens character varying(255),
  sens_iti character varying(255),
  suivi_dessinateur character varying(255),
  suivi_maj text,
  surface character varying(255),
  taille_police_nom character varying(255),
  tetra_commune character varying(255),
  tetra_ld_surfacique character varying(255),
  typ_adres character varying(255),
  type_maj character varying(255),
  type_voie character varying(255),
  vitesse_autorisee integer,
  vitesse_moyenne integer,
  z double precision,
  z_fin double precision,
  z_ini double precision,
  z_level_entrant integer,
  z_level_sortant integer,
  geometrie geometry(MultiLineString,27572),
  nbre_voies character varying(255),
  nbre_chaussees character varying(255),
  CONSTRAINT pk_rerousecon_l PRIMARY KEY (fk_sdis33_prevision)
)
WITH (
  OIDS=TRUE
);
ALTER TABLE neogeo.rerousecon_l
  OWNER TO gis_admin;

-- Index: neogeo.sidx_rerousecon_l

-- DROP INDEX neogeo.sidx_rerousecon_l;

CREATE INDEX sidx_rerousecon_l
  ON neogeo.rerousecon_l
  USING gist
  (geometrie);
